version: '3.8'

services:
  app:
    build: ./app
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - database
      - rabbitmq

  web-proxy:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    restart: on-failure
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

  database:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres_volume:
  rabbitmq_volume:

networks:
  app-network:
    driver: bridge