version: '3.8'

services:
  app:
    build: ./app
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - database
      - rabbitmq

  web-proxy:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - app-network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

networks:
  app-network:
    driver: bridge